### ISSUE TITLE
[FEATURE] Provide endpoint for verified status

### ISSUE THREAD

**Issue by alexander-nitsche** [eliashaeussler/typo3-badges#135]
**Is your feature request related to a problem? Please describe.**
 There is a new achievement "[Verified TYPO3 extension](https://typo3.com/typo3-cms/verified-extensions-integrations-for-typo3/extensions)" and the user is not immediately aware of it on reading the README.

**Describe the solution you'd like**
I would like to use a badge with the verified status of my TYPO3 extension, provided by the TER API.

**Comment by eliashaeussler** [comment]
Hi @alexander-nitsche, this feature is now implemented and deployed to production. Badges for verified extensions can be accessed by using the `GET /badge/{extension}/verified` endpoint.

Example URL:

<https://shields.io/endpoint?url=https://typo3-badges.dev/badge/news/verified/shields>

Result:

![EXT:news](https://shields.io/endpoint?url=https://typo3-badges.dev/badge/news/verified/shields)

**Comment by alexander-nitsche** [comment]
Great!
